### ISSUE TITLE
자바 가상머신(Java Virtual Machine)에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [Every-CS/CS-Tech-Interview#1]

**Comment by DA-97** [comment]
**Java Virtual Machine**이란 자바 프로그램 실행환경을 만들어주는 소프트웨어이다.

JVM은 자바 실행환경 JRE에 포함되어있다.

현재 사용하는 컴퓨터의 OS에 맞는 자바 실행환경이 설치되어있다면 JVM이 설치 되어 있다는 뜻이다.

자바 코드를 텀파일 하여 .class 바이트 코드로 만들면 해당 코드가 자바 가상 머신 환경에서 실행되고, JVM이 운영체제에 맞는 실행 파일로 바꿔주기 때문에 윈도우, 리눅스에서 따로 컴파일해준 필요가 없다.
(*윈도우에 설치되어있는 JVM과 리눅스에 설치되어있는 JVM은 서로 다르다.)

**Comment by import-max** [comment]
- 자바 코드를 실행하기 위한 가상환경을 만들어주는 소프트웨어이다. Java는 OS에 종속되지 않기 때문에 실행하기 위해서는 실행시킬 어떤 도구가 필요하다. 이 때 OS에 종속받지 않고 CPU 가 Java를 인식, 실행할 수 있게 하는 가상 컴퓨터이다.
- 크게 클래스 로더(Class Loader), 실행 엔진(Execution Engine), 런타임 데이터 영역 (Runtime Data Area)으로 구성되어 있다.

**Comment by hkwon0625** [comment]
자바 프로그램이 어느 기기나 운영체제 상에서도 실행될 수 있도록 하기 위해 JVM은 자바 애플리케이션을 클래스 로더를 통해 읽어들이고, JAVA와 OS 사이에서 중개자 역할을 수행한다.
JVM 실행에 있어서 가장 일반적인 상호작용은, 힙과 스택의 메모리 사용을 확인하는 것이다. 또한 가비지 컬렉션(Garbage Collection)이라는 프로세스를 통해 메모리를 관리한다.

**Comment by haileyKimDev** [comment]
가상 머신이란 프로그램을 실행하기위한 컴퓨터와 유사한 머신을 소프트웨어로 구현한 것을 말하며, 자바 바이트 코드를 해석하고 실행하는 역할을 JVM이한다. 자바 애플리케이션을 클래스 로더를 통해 읽어들여서 자바 API와함께 실행한다.
