### ISSUE TITLE
SQL과 NOSQL의 차이에 대해 설명해주세요.

### ISSUE THREAD

**Issue by hkwon0625** [Every-CS/CS-Tech-Interview#10]

**Comment by haileyKimDev** [comment]
SQL은 관계형 데이터구조를 NoSQL은 비관계형 데이터 구조를 말한다. SQL 은 관계형데이터베이스 시스템(RDBMS)에서 데이터를 저장,수정,삭제 및 검색 할 수 있다. 정해진 스키마를 따라 테이블에 저장된다. 데이터들을 여러개의 테이블에 나눠서 저장해 데이터들의 중복을 피한다.

NoSQL은 비관계형 데이터베이스를 말하며 키-값 데이터베이스, 더큐먼트 데이터베이스등이 있다. 스키마 선언없이 필드의 추가,삭제가 자유로우며 서버 확장에 용이하다.

**Comment by DA-97** [comment]
> **특징 및 장점 비교**

**SQL특징**
- 수직적 확장만 지원
- 명확한 스키마, 데이터 무결성 보장
- 관계는 각 데이터를 중복없이 한번만 저장
- 관계를 맺고 있는 데이터가 자주 변경되는 애플리케이션의 경우 적합
- 명확한 스키마와 사용자가 데이터에게 중요한 경우 적합

**SQL 종류**
- Oracle DB
- IBM DB2
- MS SQL Server
- PosgreSQL
- MySQL
- SQLite

---
**NoSQL특징**

- 수직/수평적 확장 지원
- 스키마X, 유연함
- 데이터 읽는 속도가 빠름
- 정확한 데이터 구조를 알 수 없거나, 변경/확장될 예정인 경우 적합
- 잦은 데이터 읽기, 드문 데이터 변경인 경우 적합
- 막대한 양의 데이터를 다룰 경우 (수평확장) 적합

**NoSQL의 종류**
- Key-Value DB : Redis, Oracle NoSQL DB
- Wide-Columm DB : Hbase, GoogleBigTable, Vertica
- Document DB : omnggoDB, CouchDB, Azure Cosmos DB
- Graph DB : Neo4j, BlazeGraph, OrientDB

**Comment by hkwon0625** [comment]
**SQL/RDB 특징**

1. 관계형 데이터 모델로써 모든 데이터를 2차원 테이블 형태로 표현
2. 트랜젝션(Transection), ACID(Atomicity, Consistency, Isolation, Durability)등의 개념이 특징
3. Data를 Column과 Row형태로 저장
4. Schema 규격
5. SQL이 강력해 복잡한 질의 가능
6. 분산 및 확장 어려움

**NoSQL 특징**

1. Not Only SQL, “관계형이지 않은”(여집합) DB를 아우르기 때문에 종류가 매우 다양
2. Eventual Consistency + CAP(Consistency, Availability, Partition Tolerance)의 개념이 특징
3. Key-value, Column-based, Document, Graph 등 데이터 모델이 다양
4. 특정 도메인에 고성능/최적화_(가령 소셜 네트워크를 사업 도메인으로 하는 회사에서 인간 관계는 모두 그래프이기 때문에 그래프 데이터베이스를 사용하면 그래프에 최적화된 API를 사용할 수 있고 데이터베이스 성능도 향상시킬 수 있다.)_
5. 분산형의 특징으로 수평적 확장(Scale out)이 매우 용이
6. 질의 언어가 저수준이라 기교가 필요(join이 불가능 하기에 컬렉션을 통하여 데이터 산출), 자주 변경되는 데이터에는 부적합

**Comment by import-max** [comment]
* SQL
   - 관계형 데이터베이스로, 정해진 데이터 스키마에 따라 테이블에 저장된다.
   - 관계를 통해 여러 테이블에 분산된다.
   - 스키마를 준수하지 않은 레코드는 테이블에 추가할 수 없다.
* NOSQL
  - 관계형 데이터베이스의 반대말로 스키마도 없고 관계도 없다.
  - json과 비슷한 형태로 가지고 있다.
  - 여러 컬럼을 작성할 때 여러 테이블에 조인할 필요없이 (join이라는 개념이 없다.) 모든 것을 갖춘 문서를 작성한다.
