### ISSUE TITLE
캐시메모리에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [Every-CS/CS-Tech-Interview#2]

**Comment by DA-97** [comment]
CPU와 메인 메모리 사이의 속도차이를 줄이기 위한 메모리장치이다.
+
RAM(Memory)에서 데이터를 인출해오는 속도가 CPU의 데이터 처리속도를 따라가지 못하여 병목현상이 발생하는데, 이를 완화하기 위해 캐시메모리를 중간에 두고 둘 사이의 데이터를 전달해준다.

**Comment by import-max** [comment]
- 속도가 빠른 장치와 느린 장치에서 속도 차이에 따른 병목 현상을 줄이기 위한 메모리를 말한다. CPU가 주기억장치에서 저장된 데이터를 읽어올 때, 자주 사용하는 데이터를 캐시 메모리에 저장한 뒤, 다음에 이용할 때 주기억장치가 아닌 캐시 메모리에서 먼저 가져오면서 속도를 향상시킨다.
- 속도와 크기에 따라 분류한 것으로, 일반적으로 L1 캐시부터 먼저 사용된다. (CPU에서 가장 빠르게 접근하고, 여기서 데이터를 찾지 못하면 L2로 가고 그 다음 L3 이 실행된다.)
- 캐시 메모리를 사용할 때는 공간적, 시간적 지역성을 고려해야 하고 이를 제대로 고려하지 못 했을 때 Cold miss, Conflict miss, Capacity miss 등이 발생할 수 있다.

**Comment by hkwon0625** [comment]
CPU가 주기억장치에서 저장된 데이터를 읽어올 때, 자주 사용하는 데이터를 캐시 메모리에 저장한 뒤, 다음에 이용할 때 주기억장치가 아닌 캐시 메모리에서 먼저 가져오면서 속도를 향상시킨다.
캐시 메모리 작동 원리에는 시간 지역성과 공간 지역성의 원리가 존재한다.  
캐시 미스에는 cold miss, conflict miss, capacity miss가 있다.
캐시 메모리 구조로는 direct mapped cache, fully associative cache, set associative cache가 있다.

**Comment by haileyKimDev** [comment]
캐시 메모리는 CPU와 메인 메모리 사이에 있지만, CPU내에 존재할 수도 있고 역할이나 성능에 따라서는 CPU밖에 존재할 수도 있다. 빠른 CPU의 처리속도와 상대적으로 느린 메인 메모리에서의 속도의 차이를 극복하는 중간 버퍼 역할을 한다. CPU는 빠르게 일을 진행하고 있는데, 메모리에서 데이터를 가져오고 가져가는데 느려서 중간에 미리 CPU에 전달될 데이터를 들고 서 있는 형태라고 말할 수 있다.
