### ISSUE TITLE
프로세스와 스레드의 차이에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [Every-CS/CS-Tech-Interview#3]

**Comment by DA-97** [comment]
**프로세스**

운영제체로부터 자원을 할당받는 작업의 단위이다.
=> 프로그램이 실행되면 프로세스의 상태가 된다.

**스레드**

할당 받은 자원을 이용하는 실행의 단위로 프로세스 내에 여러개의 스레드가 생길 수 있다. 각각의 스레드는 프로세스내의 공통 자원을 공유한다.

**멀티프로세스**

하나의 프로그램을 여러개의 프로세스로 구성하여 각 프로세스가 하나의 작업(task)를 처리하는 구조

- 하나의 프로세스가 잘못되어도 프로그램은 동작된다.
- context wsitching이 많아져서 성능 저하의 우려가 있다.

**멀티스레드**

프로그램을 여러개의 스레드로 구성하고 각 스레드가 작업(task)를 처리하는구조

- 비교적 멀티 프로세스보다 멀티스레드를 할당하는 것이 비용이 적다.
- 하나의 스레드에서 오류가 생기면 전체 프로세스에 오류가 발생된다.
- 자원을 공유 하기 때문에 너무 많은 스레드는 오버헤드를 발생시킨다.

**Comment by import-max** [comment]
- 프로세스는 실행파일로 .exe 형태로 실행되기도 하고, 메모리에 올라와서 연속적으로 실행되고 있는 프로그램의 인스턴스라고 할 수 있다. 각각 독립된 메모리 영역(Stack, Code, Data, Heap)을 할당받는다.
- 스레드는 프로세스 내에서 실행되는 여러 흐름의 단위로, 프로세스의 특정한 수행 경로를 의미하기도 한다. 프로세스 내에서 각각 stack만 따로 할당받고 Code, Data, Heap은 공유한다.

**Comment by hkwon0625** [comment]
프로세스는 컴퓨터에서 연속적으로 실행되고 있는 컴퓨터 프로그램을 의미한다. code, data, stack, heap의 구조로 되어 있는 독립된 메모리 영역이 있다. 각 프로세스는 별도의 주소 공간에서 실행되며, 한 프로세스는 다른 프로세스의 변수나 자료구조에 접근할 수 없기 때문에 해킹과 같은 위험으로부터 메모리를 보호할 수 있다. 자원을 공유하지 않기 때문에 캐쉬 메모리 초기화, context switching과 같은 작업이 이루어지고 오버헤드가 발생하게 된다.
스레드는 프로세스 내에서 실행되는 여러 흐름의 단위이다. 스레드는 프로세스 내에서 각각 stack만 따로 할당받고, code, data, heap 영역은 공유한다. 메모리를 공유하기 때문에 시스템 자원 소모가 줄어들고 응답 시간도 단축된다. 하지만 데이터 충돌과 버그 발생 가능성이 증가하게 된다.
