### ISSUE TITLE
OSI 7계층에 대해 아는대로 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [Every-CS/CS-Tech-Interview#4]

**Comment by DA-97** [comment]
### osi 7 layer (open systems interconnection 7 layer)
> 다양한 시스템들이 서로 통신할 수 있게 개발된 네트워크 아키텍처로 참조 모델로 사용되고있다. 
각 계층의 통신 표준화를 통해 장비별 포트, 프로토콜의 호환성을 높이고 시스템상의 문제를 빠르게 파악할 수있다.
각 계층의 통신 방법에 따라 7계층으로 나뉘어있다.

### 애플리케이션(7)

> 사용자가 Network 관련 서비스를 이용할 수 있도록 해준다.
통신단위 : data (message)
프로토콜 : DNS, HTTP, DHCP

### 표현(6)
> 데이터 표현 방식을 관리하는 계층, 데이터 변환, 암호화, 압축 등을 담당한다.
통신단위 : data (message)
프로토콜 : JPEG, MPEG

### 세션(5)
> 인터페이스 간의 연결을 구성하는 역할로 Port를 통해 통신된다.
통신단위 : data (message)
프로토콜 : SSH, Telnet, TLS

### 전송(4)
> 네트워크 계층을 통해 연결된 네트워크를 통해 데이터를 전송해준다.
통신단위 : Segment
프로토콜 : TCP, UDP
전용장비 : GateWay , L4 스위치

### 네트워크(3)
> 데이터를 전달하기 위해, 목적지에 대한 주소를 정하고 경로를 선택해준다.
통신단위 : Packet
프로토콜 : IP, ICMP
대표장비 : 라우터, L3스위치

### 데이터링크(2)
> 네트워크 기기 사이의 데이터를 전송하는 계층으로 물리 계층을 통해 송수신 되는 정보의 오류와 흐름을 관리한다.
통신단위 : Frame
프로토콜 : 이더넷, MAC
대표장비 : 브릿지, 스위치

### 물리(1)
> 전기신호를 이용하여 통신장비로 데이터를 전송한다.
통신단위 : bit(1,0)
프로토콜 : Modem, cable
대표장비 : Hub, 리피터

**Comment by import-max** [comment]
- 네트워크에서 통신이 일어나는 과정을 7단계로 나눈 것으로, 네트워크 이상이 생기면 문제를 찾고 해당 계층만 고치면 된다. OSI 7계층 이전에는 표준화가 안 되어 있어 각자만의 방식으로 개발을 해서 통신에 어려움이 있었다.
- 보통 하위 계층일수록 하드웨어나 로우 레벨에 가깝고, 상위 계층일수록 소프트웨어나 하이 레벨 (응용, 유저 반응 등)에 가깝다.

**Comment by hkwon0625** [comment]
OSI 7계층은 네트워크 통신이 일어나는 과정을 7단계로 나눈 모델로, 7계층 중 어느 구간에서 생긴 네트워크 문제인지 파악하는 것을 돕는다.
Physical layer, Datalink layer, Network layer, Transport layer, Session layer, Presentation layer, Application layer로 나누어진다.
각 계층마다 목적에 맞는 대표적인 장비, 프로토콜이 있다.
