### ISSUE TITLE
tcp와 udp의 특징 및 차이에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [Every-CS/CS-Tech-Interview#5]

**Comment by DA-97** [comment]
**TCP**
- 네트워크 계층 중 전송 계층에서 사용하는 프로토콜이다.
- 장치들 사이에 접속을 위하여 장치의 연결을 설정해 신뢰성을 보장한다.
- TCP 통신을 이용하여 데이터를 전송할 때는 3-way handshake를 통해 연결 설정하고, 4-way handshake 를 통해 해제 할 수 있다.
- handshake 과정을 통하기 때문에 신뢰성이 높은 대신 udp에 비해 속도가 느리다.

**UDP**
- 네트워크 계층 중 전송 계층에서 사용하는 프로토콜이다.
- 장치들 사이에 접속을 위하여 연결을 설정한다. udp는 신뢰성보다는 연속성이 중요한 비 연결형 서비스다.
- tcp와 다르게 정보를 주고 받을 때 신호를 보내더나 받는 절차를 거치지 않는다.
- tcp보다 속도가 빠르지만, 신뢰성은 낮다.

**Comment by import-max** [comment]
- tcp는 **두 개의 호스트를 연결하고 데이터 스트림을 교환하게 해주는 중요한 네트워크 프로토콜**
이다. TCP는 데이터와 패킷이 보내진 순서대로 전달하는 것을 보장해준다.
- udp는 User Datagram Protocol의 축약어로 **컴퓨터가 다른 컴퓨터와 데이터 통신을 하기 위한 규약(프로토콜)의 일종**
이다. UDP는 세계 통신표준으로 개발된 OSI 모형에서 4번째 계층인 전송 계층(Transport Layer)에서 사용하는 규약이다.
- tcp 소켓에서는 통신이 이루어지기 전에 **connect, listen, accept**하는 과정이 있는데, udp에서는 없음
- tcp 소켓은 데이터 소실 x, 순서 보장
- udp 소켓은 데이터가 소실될 수 있고, 순서가 지켜지지 않을 수 있다.

![image](https://user-images.githubusercontent.com/68390559/205478301-a94f8833-0491-4eb6-a172-354196855bdf.png)

**Comment by hkwon0625** [comment]
**TCP**
3 way handshaking을 통한 연결을 맺으므로 높은 신뢰성을 보장한다. 데이터가 소실되면 안 되는 파일 전송에 적합한 방식이다. UDP에 비해 헤더에 많은 정보를 담고 있기 때문에 크기가 상대적으로 크고 느리다.

**UDP**
비연결형 방식으로 실시간 스트리밍 서비스와 같은 간단한 데이터를 빠른 속도로 전송하고자 하는 어플리케이션에 적절하다.
