### ISSUE TITLE
쿠키와 세션의 특징 및 차이에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [Every-CS/CS-Tech-Interview#6]

**Comment by DA-97** [comment]
**쿠키(Cookie)**
- 클라이언트 (브라우저) 로컬에 저장되는 유저의 인증 및 다양한 정보를 가지는 데이터 파일이다.
- 특정 웹사이트에 접속해서 쿠키를 저장했다면, 다음에 해당 브라우저에 접속할 때 쿠키에 저장된 정보를 통해 그때 설정된 **값**을 그대로 보여준다.
- 도메인에 국한된다.
- 인증에 대한 유효시간이 있다.

**세션(Session)**
- 브라우저가 유저의 세션 ID를 쿠키를 통해 서버에 전달(자동)하면, 세션DB에서 해당 유저를 찾고, 서버는 이제서야 해당 유저를 인식하게 된다.

=> 즉 쿠키는 매개체, 세션은 서버에서 유저를 인식하는 방식 중 하나이다.

**Comment by import-max** [comment]
### 쿠키

- 쿠키는 클라이언트 로컬에 저장되는 key, value가 들어있는 데이터 파일이다. 클라이언트의 상태 정보를 로컬에 저장했다가 참조하며 사용자가 따로 요청하지 않아도 브라우저가 요청 시에 Request Header를 넣어서 자동으로 서버에 전송한다.
- 동작 방식
    - 클라이언트가 페이지를 요청 → 서버에서 쿠키 생성 → HTTP 헤더에 쿠키를 포함시켜 응답 → 브라우저가 종료되어도 쿠키 만료 기간이 있다면 클라이언트에서 보관 → 같은 요청을 할 경우 HTTP 헤더에 쿠키를 함께 보냄 → 서버에서 쿠키를 읽어 이전 상태 정보를 변경할 필요가 있을 때 쿠키를 업데이트하여 변경된 쿠키를 HTTP 헤더에 포함시켜 응답

### 세션

- 세션은 쿠키를 기반하고 있지만, 서버 측에서 관리한다. 서버에서는 클라이언트를 구분하기 위해 세션 ID를 부여하며 웹 브라우저가 서버에 접속해서 브라우저를 종료할 때까지 인증 상태를 유지한다.
- 접속 시간에 제한을 둔다. 사용자에 대한 정보를 서버에 두기 때문에 쿠키보다 보안에 좋지만, 사용자가 많아질수록 서버 메모리를 많이 차지하게 된다. 예를 들어 동시접속자 수가 많은 웹 사이트인 경우 서버에 과부하를 주게 되므로 성능 저하의 요인이 된다. 
클라이언트가 Request를 보내면, 해당 서버의 엔진이 클라이언트에게 유일한 ID(세션ID)를 부여한다.

**Comment by hkwon0625** [comment]
HTTP는 Connectionless이자 Stateless이기 때문에 쿠키와 세션을 통해서 데이터를 유지한다.
**쿠키**는 클라이언트(브라우저) 로컬에 저장된다. 이름, 값, 만료 날짜, 도메인, 경로 정보가 포함되어 있다. 4kb 크기이며, 도메인당 20개의 쿠키를 저장할 수 있다. 지워져도 상관 없고, 타인이 가져가도 문제가 없는 정보들을 담고 있다. 쿠키의 사용 예시로는 팝업에서 '오늘 이 창을 더 이상 보지 않음'에 체크하는 경우가 있다.
**세션**은 사용자 정보 파일을 서버 측에서 관리한다. 서버 메모리에 따라 저장할 수 있는 개수가 다르다. 클라이언트가 발급 받은 세션 ID를 쿠키를 사용해서 서버에 전달하면 이 세션 ID를 가지고 서버는 클라이언트 정보를 가져와 응답한다. 세션에는 타인에게 노출되면 안되는 중요 정보를 저장한다. 예시로는 자동 로그인이 있다.
