### ISSUE TITLE
브라우저 동작 방법에 대해 설명해주세요.

### ISSUE THREAD

**Issue by import-max** [Every-CS/CS-Tech-Interview#7]

**Comment by DA-97** [comment]
1. 사용자가 크롬(웹브라우저) 검색창에 특정 사이트 주소를 입력한다.
2. 크롬(웹브라우저)가 DNS에게 특정 사이트의 도메인을 요청한다.
3. DNS가 크롬(웹브라우저)에게 사이트의 IP 주소를 응답한다.
4. 크롬(웹브라우저)가 웹 서버에게 ip 주소를 이용하여 html을 요청한다.
5. 웹 서버는 웹 애플리케이션 서버와 데이터 베이스에서 웹페이지 작업을 처리한다.
6. 작업 처리 결과를 웹 서버로 보낸다.
7. 웹서버는 크롬(웹브라우저)에게 html 문서 결과를 응답한다.
8. 크롬(웹브라우저)는 화면에 웹 페이지를 출력한다.

**Comment by import-max** [comment]
- 사용자가 선택한 자원을 서버에 요청하여 브라우저에 표시하게 된다. 여기서 자원은 html 문서, pdf, image 등 다양한 형태로 되어 있으며 자원의 주소는 URL에 의해 정해진다.

**Comment by hkwon0625** [comment]
사용자가 naver.com과 같은 URL을 웹브라우저 주소창에 입력하면, 도메인에 매핑된 IP 주소를 알아내기 위해 DNS 질의를 하게 된다.
가장 가까운 DNS 서버에 UDP 방식으로 질의를 하게 되고, 응답이 없을 경우 루트 도메인 네임서버에 질의한다. 이 경우 tcp 방식을 사용한다. .com, .edu, .org등 주소에 따라 질의하는 top-level 서버가 다르다.
