### ISSUE TITLE
64비트와 32비트의 차이가 무엇인가요?

### ISSUE THREAD

**Issue by import-max** [Every-CS/CS-Tech-Interview#8]

**Comment by DA-97** [comment]
**32, 64bit 는 CPU안의 레지스터(메모리)를 이용해서 한번에 처리할 수 있는 데이터의 크기를 뜻한다.**

CPU는 0,1 두개의 비트로만 표현할 수 있기 때문에

32bit = 2^32 = 4,294,967,296 = 약 4GB
64bit = 2^64 = 18,446,744,073,709,551,616 = 약 18 EB

매우 큰 차이가 난다.

**따라서 32bit의 레지스터를 가지는 컴퓨터가 64bit 프로그램을 설치하면 실행되지 않지만, 64bit의 컴퓨터가 32bit프로그램을 설치하면 문제없이 실행된다.**

**Comment by import-max** [comment]
- 비트는 컴퓨터 처리 정보의 최소 단위인데 2진수의 나열로 이루어진다. 32비트는 $2^{32}$, 64비트는 $2^{64}$ 공간의 주소를 가지게 된다. 이 공간이 32비트는 4GB라서, 32비트는 4기가까지만 처리가 가능하고 64비트가 되는 순간 메모리 공간이 비약적으로 커지기 때문에 대용량 처리가 가능하다.
- 32비트와 64비트의 차이는 저장 장치의 bit 폭이 다르다는 점이다. 이 크기가 클수록 처리할 수 있는 정보의 크기가 늘어난다. 64비트가 32비트의 데이터를 처리할 수는 있지만 32비트가 64비트의 데이터를 처리할 수는 없다.

**Comment by hkwon0625** [comment]
CPU는 작업을 수행 할 때, 레지스터에 있는 데이터를 가지고 연산을 한다. 이 때 64비트 프로세서는 레지스터의 길이가 64비트로 길어지면서 한 번에 더 많은 정보를 캐시할 수 있다.
